"""rename department

Revision ID: 169c65483b01
Revises: adb25b013551
Create Date: 2025-01-15 12:40:36.450541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169c65483b01'
down_revision = 'adb25b013551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
